### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sapiet** [ZeProf2C/opclionicCD#1]
Erreur durant le ionic serve:
TypeError: Cannot read property 'pipe' of undefined

at Promise (/usr/local/lib/node_modules/ionic/lib/serve.js:450:22)
at new Promise (<anonymous>)
at IonicAngularServeCLI.spawn (/usr/local/lib/node_modules/ionic/lib/serve.js:421:16)

[ERROR] ionic-app-scripts has unexpectedly closed (exit code -13).
        
        The Ionic CLI will exit. Please check any output above for error details.

**Comment by sapiet** [comment]
un rm -rf node_modules && npm i a résolu le soucis, pas compris
